
version: "3"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: rxcE3RGw9c
      POSTGRES_USER: kitchenman-user
      POSTGRES_DB: kitchenman
  api:
    image: softwaresale/kitchenman-api:latest
    ports:
      - "3000:3000"
    volumes:
      - "/var/log/kitchenman-api/:/var/log/kitchenman-api"
    deploy:
      replicas: 1 
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    links:
      - "db:database"
    depends_on:
      - db
