
version: "3"
services:
  db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: rxcE3RGw9c
      POSTGRES_USER: kitchenman-user
      POSTGRES_DB: kitchenman
    networks:
      - default 
  api:
    image: softwaresale/kitchenman-api:latest
    ports:
      - "3001:3000"
    deploy:
      replicas: 1 
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    depends_on:
      - db
    networks:
      - default
  server:
    image: softwaresale/kitchenman-server:latest
    ports:
      - "80:80"
      - "8000:80"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    depends_on:
      - db
      - api
    networks:
      - default

